name: Publish Plugin

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      # See: https://docs.gradle.org/current/userguide/signing_plugin.html#sec:in-memory-keys
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNINGKEY }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PARAPHRASE }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish artifacts
        run: ./gradlew :plugin-build:tailwind-kt:publish --stacktrace
